### ISSUE TITLE
Support ESLint 7.x

### ISSUE THREAD

**Issue by BePo65** [Turbo87/eslint-plugin-chai-expect#107]
ESLint [v7.0.0](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) is released .

It would be awesome to have official ESLint 7 support for the release on npmjs.
As I can see, the master branch depends on eslint@^7.0.0 already, but the peerDependency is still  "peerDependencies": {"eslint": ">=2.0.0 <= 6.x"}.

**Comment by brettz9** [comment]
This can be closed I think as per b70e7761718c61f30c58fd557b297bcf2e69fd69

**Comment by Turbo87** [comment]
yep, thanks!
