### ISSUE TITLE
Prevent expect(true).to.be.false

### ISSUE THREAD

**Issue by Turbo87** [Turbo87/eslint-plugin-chai-expect#17]
... or any other primitive value inside `expect()` as this is usually a sign of a bug in the test code.

Example: https://github.com/ember-cli/ember-cli/pull/6846

**Comment by brettz9** [comment]
Would you want to avoid preventing object and array literals as well, or would you be concerned that people might have a use for something like:

```js
expect({
    result1, result2
}).to.deep.equal(expected);
```

**Comment by Turbo87** [comment]
no, I think objects and arrays are fine. by "primitive values" I meant numbers, booleans, strings, null and undefined.

**Comment by brettz9** [comment]
Ok, sure. In testing a little, it seems that regex literals also have the `LITERAL` AST. You want that flagged like the other literals? I'd assume yes, since there is no dynamic content in it...

**Comment by Turbo87** [comment]
yeah, sounds like a good idea 👍
