### ISSUE TITLE
Add 'json' to the terminating-properties rule

### ISSUE THREAD

**Issue by whamondg** [Turbo87/eslint-plugin-chai-expect#18]
Currently the 'terminating-properties' rule will not pick up on the incorrect usage of ```expect(result).to.be.json()```

**Comment by whamondg** [comment]
I've raised a PR (#19) which adds this feature.

**Comment by Turbo87** [comment]
where is `.json` coming from? it doesn't seem to be a part of the official Chai.js API

**Comment by whamondg** [comment]
Sorry, I just realised it's coming in from https://github.com/chaijs/chai-http which adds several additional terminating-properties:

- headers
- html
- ip
- json
- redirect
- text

If you are interested in supporting those extensions I'll rework the PR to include them all.  If you want to keep this purely for core Chai then no worries.

**Comment by Turbo87** [comment]
> If you are interested in supporting those extensions I'll rework the PR to include them all

I don't think we should support them by default, but we could probably make the rule configurable so that you could add custom props like those.

**Comment by whamondg** [comment]
I've altered the PR and had a go at making the rule configurable to take a list of additional terminators.  Let me know what you think.

**Comment by whamondg** [comment]
If it looks reasonable I'll document it up before the PR is merged

**Comment by whamondg** [comment]
Documentation added in https://github.com/Turbo87/eslint-plugin-chai-expect/pull/23

**Comment by whamondg** [comment]
Thanks for merging in the PRs.  Do you have a rough idea when you will push up a new release to NPM?

**Comment by Turbo87** [comment]
my plan was to wait until https://github.com/Turbo87/eslint-plugin-chai-expect/pull/22 is done too

**Comment by whamondg** [comment]
OK thanks.  I'll keep an eye out

**Comment by Turbo87** [comment]
closing, as this has been released quite a while ago 😅
