### ISSUE TITLE
Combine with eslint-plugin-chai-friendly

### ISSUE THREAD

**Issue by astorije** [Turbo87/eslint-plugin-chai-expect#25]
Hey @Turbo87!

It would be nice if you could combine your plugin with @ihordiachenko's [`eslint-plugin-chai-friendly`](https://github.com/ihordiachenko/eslint-plugin-chai-friendly) into a shared `eslint-plugin-chai` :)

That's even something you could submit to the other members of the https://github.com/chaijs org 🙂

---
EDIT: Counterpart of https://github.com/ihordiachenko/eslint-plugin-chai-friendly/issues/5, sorry for the spam 😅

**Comment by JustFly1984** [comment]
chai friendly is not supported and last published 2 years ago
