### ISSUE TITLE
ESLint 9 / Flat config support

### ISSUE THREAD

**Issue by brettz9** [Turbo87/eslint-plugin-chai-expect#357]
Hi,

As of ESLint 8, there is now a new format for ESLint config files which requires that plugins follow a specific format. In ESLint 9, this format will be the only one available by default (and other API changes have occurred in ESLint 9 that may affect this plugin).

Info:

1. https://eslint.org/docs/latest/use/configure/configuration-files-new
1. https://eslint.org/blog/2022/08/new-config-system-part-1/
1. https://eslint.org/blog/2022/08/new-config-system-part-2/
1. https://eslint.org/docs/latest/use/configure/migration-guide

Might you update to be compatible with the new format?

Thanks!

**Comment by BePo65** [comment]
@Turbo87 are there any plans to support eslint v9 / flat configs in the near future?

**Comment by Turbo87** [comment]
I'm not currently using this project anywhere, but feel free to work on it and open a PR :)

**Comment by BePo65** [comment]
OK, gonna do it.

**Comment by Turbo87** [comment]
resolved by #378
