### ISSUE TITLE
At least one assertion

### ISSUE THREAD

**Issue by goldbergyoni** [Turbo87/eslint-plugin-chai-expect#43]
Thanks for the great work.

Would love to hear your thoughts on a check that ensure a test has at least 1 assertion (otherwise it is not doing anything...). Are you aware of one like this? would you appreciate such a PR?

**Comment by Turbo87** [comment]
> Would love to hear your thoughts on a check that ensure a test has at least 1 assertion (otherwise it is not doing anything...). Are you aware of one like this? would you appreciate such a PR?

the problem with implementing this is the coupling (or lack of coupling) between the assertion framework (chai) and the testing framework (mocha, jest, ava, ...). I think such an assertion would be better placed in an ESLint plugin for these individual frameworks (e.g. https://github.com/lo1tuma/eslint-plugin-mocha/).

the other problem is that the assertions could happen in a nested function call, which we can't easily detect from just looking at the syntax tree of the file. ultimately such a rule would probably produce too many false positives.

> Thanks for the great work.

❤️
