### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by brettz9** [Turbo87/eslint-plugin-chai-expect#89]
Thanks very much for your promptness on all the reviewing and merges...

Are you ok for a new npm release now?

**Comment by brettz9** [comment]
Were you waiting on anything else, @Turbo87 ? Thanks!

**Comment by Turbo87** [comment]
sorry, forgot about this 🙈

I'm currently on vacation, will put out a release once I'm back.

**Comment by brettz9** [comment]
Just another ping on a release...

**Comment by Turbo87** [comment]
done: https://github.com/Turbo87/eslint-plugin-chai-expect/releases/tag/v2.1.0 :)
